Repository fetch-rewards/SwiftSyntaxSugar, pull requests merged in 2025-04, with the labels that each got.

#64 Add dependencies label to docs and PR Labels workflow
  .github/pull_request_template.md
  .github/workflows/pr-labels.yml
Labels: documentation, ci/cd

#65 Add Swift version and platform badges to README
  README.md
Labels: documentation

#66 Update validate-pr-title script
  .github/scripts/validate-pr-title.js
Labels: ci/cd

#67 Remove author from file headers
  .swiftformat
  Sources/SwiftSyntaxSugar/AccessLevelSyntax/AccessLevelSyntax.swift
  Sources/SwiftSyntaxSugar/AccessorBlockSyntax/AccessorBlockSyntax+Accessors.swift
  Sources/SwiftSyntaxSugar/AccessorDeclSyntax/AccessorDeclSyntax+Effects.swift
  Sources/SwiftSyntaxSugar/ActorDeclSyntax/ActorDeclSyntax+AccessLevel.swift
  Sources/SwiftSyntaxSugar/ClassDeclSyntax/ClassDeclSyntax+AccessLevel.swift
  Sources/SwiftSyntaxSugar/DeclModifierListSyntax/DeclModifierListSyntax+AccessLevel.swift
  Sources/SwiftSyntaxSugar/DeclModifierSyntax/DeclModifierSyntax+AccessLevel.swift
  Sources/SwiftSyntaxSugar/FunctionDeclSyntax/FunctionDeclSyntax+AccessLevel.swift
  Sources/SwiftSyntaxSugar/FunctionDeclSyntax/FunctionDeclSyntax+Effects.swift
  Sources/SwiftSyntaxSugar/FunctionParameterSyntax/FunctionParameterSyntax+IsVariadic.swift
  Sources/SwiftSyntaxSugar/FunctionTypeSyntax/FunctionTypeSyntax+Escaping.swift
  Sources/SwiftSyntaxSugar/InheritanceClauseSyntax/InheritanceClauseSyntax+InheritedTypes.swift
  Sources/SwiftSyntaxSugar/InitializerDeclSyntax/InitializerDeclSyntax+AccessLevel.swift
  Sources/SwiftSyntaxSugar/MemberBlockSyntax/MemberBlockSyntax+MemberDeclarations.swift
  Sources/SwiftSyntaxSugar/ProtocolDeclSyntax/ProtocolDeclSyntax+AccessLevel.swift
  Sources/SwiftSyntaxSugar/ProtocolDeclSyntax/ProtocolDeclSyntax+Actor.swift
  Sources/SwiftSyntaxSugar/ProtocolDeclSyntax/ProtocolDeclSyntax+GenericWhereClauses.swift
  Sources/SwiftSyntaxSugar/ProtocolDeclSyntax/ProtocolDeclSyntax+Type.swift
  Sources/SwiftSyntaxSugar/StructDeclSyntax/StructDeclSyntax+AccessLevel.swift
  Sources/SwiftSyntaxSugar/SyntaxProtocol/SyntaxProtocol+WithAttributeListSyntax.swift
  Sources/SwiftSyntaxSugar/SyntaxProtocol/SyntaxProtocol+WithCodeBlockSyntax.swift
  Sources/SwiftSyntaxSugar/SyntaxProtocol/SyntaxProtocol+WithDeclModifierListSyntax.swift
  Sources/SwiftSyntaxSugar/TypeSyntax/TypeSyntax+Describing.swift
  Sources/SwiftSyntaxSugar/VariableDeclSyntax/VariableDeclSyntax+AccessLevel.swift
  Tests/SwiftSyntaxSugarTests/AccessLevelSyntax/AccessLevelSyntaxTests.swift
  Tests/SwiftSyntaxSugarTests/AccessorBlockSyntax/AccessorBlockSyntax_AccessorsTests.swift
  Tests/SwiftSyntaxSugarTests/AccessorDeclSyntax/AccessorDeclSyntax_EffectsTests.swift
  Tests/SwiftSyntaxSugarTests/ActorDeclSyntax/ActorDeclSyntax_AccessLevelTests.swift
  Tests/SwiftSyntaxSugarTests/ClassDeclSyntax/ClassDeclSyntax_AccessLevelTests.swift
  Tests/SwiftSyntaxSugarTests/DeclModifierListSyntax/DeclModifierListSyntax_AccessLevelTests.swift
  Tests/SwiftSyntaxSugarTests/DeclModifierSyntax/DeclModifierSyntax_AccessLevelTests.swift
  Tests/SwiftSyntaxSugarTests/FunctionDeclSyntax/FunctionDeclSyntax_AccessLevelTests.swift
  Tests/SwiftSyntaxSugarTests/FunctionDeclSyntax/FunctionDeclSyntax_EffectsTests.swift
  Tests/SwiftSyntaxSugarTests/FunctionParameterSyntax/FunctionParameterSyntax_IsVariadicTests.swift
  Tests/SwiftSyntaxSugarTests/FunctionTypeSyntax/FunctionTypeSyntax_EscapingTests.swift
  Tests/SwiftSyntaxSugarTests/InheritanceClauseSyntax/InheritanceClauseSyntax_InheritedTypesTests.swift
  Tests/SwiftSyntaxSugarTests/InitializerDeclSyntax/InitializerDeclSyntax_AccessLevelTests.swift
  Tests/SwiftSyntaxSugarTests/MemberBlockSyntax/MemberBlockSyntax_MemberDeclarationsTests.swift
  Tests/SwiftSyntaxSugarTests/ProtocolDeclSyntax/ProtocolDeclSyntax_AccessLevelTests.swift
  Tests/SwiftSyntaxSugarTests/ProtocolDeclSyntax/ProtocolDeclSyntax_ActorTests.swift
  Tests/SwiftSyntaxSugarTests/ProtocolDeclSyntax/ProtocolDeclSyntax_GenericWhereClausesTests.swift
  Tests/SwiftSyntaxSugarTests/ProtocolDeclSyntax/ProtocolDeclSyntax_TypeTests.swift
  Tests/SwiftSyntaxSugarTests/StructDeclSyntax/StructDeclSyntax_AccessLevelTests.swift
  Tests/SwiftSyntaxSugarTests/SyntaxProtocol/SyntaxProtocol_WithAttributeListSyntaxTests.swift
  Tests/SwiftSyntaxSugarTests/SyntaxProtocol/SyntaxProtocol_WithCodeBlockSyntaxTests.swift
  Tests/SwiftSyntaxSugarTests/SyntaxProtocol/SyntaxProtocol_WithDeclModifierListSyntaxTests.swift
  Tests/SwiftSyntaxSugarTests/TypeSyntax/TypeSyntax_DescribingTests.swift
  Tests/SwiftSyntaxSugarTests/VariableDeclSyntax/VariableDeclSyntax_AccessLevelTests.swift
Labels: formatting

#69 Update changelog
  CHANGELOG.md
Labels: documentation

#68 Fix spelling mistake
  CONTRIBUTING.md
Labels: documentation

#71 Add CODEOWNERS
  CODEOWNERS
Labels: ci/cd
